### ISSUE TITLE
Clickable Widget Team

### ISSUE THREAD

**Issue by hannahfoley-1** [hannahfoley-1/SWENG_Group_27#32]
Main Menu, with the following:
Play Demo clickable button (does nothing for now)
Play Game clickable button
Exit Game clickable button
High Score displayed

Play Game Button:
Places player in environment with a timer and points displayed
Stationary targets spawn periodically
Breaking targets increments points

Exit Game Button:
Terminates the program

**Comment by moriarci** [comment]
UI documentation for StereoKit: https://stereokit.net/Pages/Guides/User-Interface.html
